services:

  postgres:
    image: postgres:18
    container_name: fintrack-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - fintrack-postgres-data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d fintrack"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: .
    container_name: fintrack-backend
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      FRONTEND_URL: ${FRONTEND_URL}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fintrack
      SPRING_DATASOURCE_USERNAME: postgres

      SPRING_PROFILES_ACTIVE: docker


  frontend:
    build:
      context: ../Fintrack-Frontend/fintrack-frontend
      args:
        VITE_API_URL: http://localhost:8080

    container_name: fintrack-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"


volumes:
  fintrack-postgres-data: